name: Manually Release API

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version (without prefix v)
        required: true
        type: string

jobs:
  release:
    permissions:
      contents: write
    env:
      OUTPUT_DIR: "output"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Publish for each runtime
        run: |
          echo "Releasing version ${{ inputs.version }}"
          python generate-resx.py 1
          declare -a runtimes=('win-x64' 'win-arm64' 'linux-x64' 'linux-arm64' 'osx-x64' 'osx-arm64')
          cd "$OUTPUT_DIR"
          for r in "${runtimes[@]}"
          do
            releaseName="Hitorus-v${{ inputs.version }}-$r"
            dotnet publish ../src/Hitorus.Api --output "$releaseName" -r "$r"
            mkdir "$releaseName/Galleries"
            zip -r "$releaseName.zip" "$releaseName"
          done
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ format('{0}/*.zip', env.OUTPUT_DIR) }}
          tag: ${{ format('v{0}', inputs.version ) }}
