name: Release API

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  check-target-file-changed:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ fromJson(steps.changed-files.outputs.any_changed) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: src/Hitorus.Api/Hitorus.Api.csproj

  get-current-version:
    runs-on: ubuntu-latest
    needs: check-target-file-changed
    outputs:
      version: ${{ steps.parse-file.outputs.value }}
    steps:
      - id: parse-file
        run: |
          currentVersion=$(cat 'src/Hitorus.Api/Hitorus.Api.csproj' | sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p')
          echo "value=$currentVersion" >> $GITHUB_OUTPUT

  get-latest-release-version:
    runs-on: ubuntu-latest
    needs: get-current-version
    outputs:
      version: ${{ steps.trim-prefix.outputs.value }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: git fetch --tags origin
      - id: get-prev-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          prefix: v
          fallback: v0.0.0
      - id: trim-prefix
        env:
          TAG_WITH_V: ${{steps.get-prev-tag.outputs.tag}}
        run: echo "value=${TAG_WITH_V:1}" >> $GITHUB_OUTPUT

  compare-versions:
    runs-on: ubuntu-latest
    needs: [get-current-version, get-latest-release-version]
    outputs:
      description: returns true if versions are equal, otherwise false
      value: ${{ fromJson(steps.compare.outputs.value) }}
    steps:
      - id: compare
        run: |
          echo "value=${{ needs.get-current-version.outputs.version == needs.get-latest-release-version.outputs.version }}" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-latest
    needs: [get-current-version, compare-versions]
    if: ${{ !(needs.compare-versions.outputs.value) }}
    steps:
      - run: echo "Releasing version ${{ needs.get-current-version.outputs.version }}!!!"
