name: Release API

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: src/Hitorus.Api/Hitorus.Api.csproj

      - name: Set CURRENT_VERSION env value
        run: |
          currentVersion=$(cat 'src/Hitorus.Api/Hitorus.Api.csproj' | sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p')
          echo "CURRENT_VERSION=$currentVersion" >> $GITHUB_ENV

      - run: git fetch --tags origin
      - name: Get previous tag
        id: previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          fallback: v0.0.0

      - name: Set LATEST_TAG env value
        run: |
          echo "LATEST_TAG=${{steps.previous-tag.outputs.tag}}" >> $GITHUB_ENV

      - name: Test if steps.changed-files.outputs.any_changed condition run
        if: ${{ steps.changed-files.outputs.any_changed == true }}
        run: echo "steps.changed-files.outputs.any_changed is true and this step was run!!!"

      - name: Print everything
        run: |
          echo "CURRENT_VERSION = $CURRENT_VERSION"
          echo "LATEST_TAG = $LATEST_TAG"
          [ "$CURRENT_VERSION" == "$LATEST_TAG" ] && echo "version equal" || echo "version not equal"
          echo "any_changed = ${{steps.changed-files.outputs.any_changed}}"